---
# Whether this playbook is targeting an actual Pi or a non-Pi environment.
deploy_target_is_pi: true

# Temperature monitor app variables.
temperature_monitor_dir: /home/pi/temperature-monitor
temperature_monitor_user: pi

# Dashboard and sensor configuration. Make sure you *remove* any variables here
# if you want to be able to override the variables per-host in host_vars.
dashboard_uri: http://10.0.1.33:3000
local_temp_read_delay: 60
local_temp_offset: 0
local_sensor_id: 1
nest_sensor_id: 3
wu_sensor_id: 2
owm_sensor_id: 2
owm_city_id: "4407084"

# Raspberry Pi configuration.
raspberry_pi_boot_config_options:
  # Set the GPU memory split value to conserve system RAM.
  - regexp: "^#?gpu_mem"
    line: "gpu_mem=16"
  # Enable 1-Wire via GPIO.
  - regexp: "^dtoverlay=w1-gpio"
    line: "dtoverlay=w1-gpio"
  # Turn off the PWR LED.
  - regexp: "^dtparam=pwr_led_trigger="
    line: "dtparam=pwr_led_trigger=none"
  - regexp: "^dtparam=pwr_led_activelow="
    line: "dtparam=pwr_led_activelow=off"
raspberry_pi_rc_local_options:
  # Disable HDMI on startup (for power savings).
  - regexp: "^/usr/bin/tvservice"
    line: "/usr/bin/tvservice -o"

# Remote Sensor configuration
station_id: 'env-sensor-00'
station_name: 'Living Room'
sensor: 'DS18B20'

# InfluxDB configuration
influxdb_token: 1234
influxdb_org: 5146
influxdb_url: http://mon.krispayne.net:8086
influxdb_bucket: House Temperatures

# Nest credentials (if empty, will not be used).
nest_access_token: ""
nest_thermostat_id: ""

# Weather Underground credentials (if empty, will not be used).
wu_api_key: ""
wu_location: "MO/Saint_Louis"
